export const subject = [
  "Corporate Accounting",
  "Business Law",
  "Macro Economics",
  "Business Statistics",
  "Environment Science and Sustainability",
  "Corporate Finance",
  "Business Ethics and CSR",
  "Investment and Portfolio Management",
  "Marketing Management",
  "Data analysis with Spreadsheets (Lab Based)",
  "Income Tax Laws",
  "Project Management",
  "Good and Service Tax(GST)",
  "E-Commerce",
  "E-Commerce Lab",
  "Environmental Science (NUES)",
  "Introduction to Derivatives",
  "Cost Accounting",
  "Decision Techniques for Business",
  "Business Environment",
  "E-Commerce",
  "Business Communication",
  "E-Commerce Lab",
  "Business Analytics",
  "Financial Management",
  "Corporate Governance, Ethics & Social Responsibility of Business",
  "Income Tax Law and Practice",
  "Sales Management",
  "Financial Markets and Institutions",
  "Project Management",
  "Digital Marketing",
  "International Business Management",
  "Business Policy & Strategy",
  "Sales & Distribution Management",
];

export const classes = [
  "BCA - I",
  "BCA - II",
  "BCA - III",
  "BCA - IV",
  "BCA - V",
  "BCA - VI",
]
